package main

import (
	"os"
	"path/filepath"
	"testing"
)

// v2.1 split the old isConfigured() gate into two independent checks:
//   isSetUp(dir)        → config.json exists (the wizard ran). Telegram-free.
//   telegramEnabled(dir) → .env carries a non-empty TELEGRAM_BOT_TOKEN.
// A desktop-only install is set up but not Telegram-enabled, which is the
// whole point of v2.1 — so these are tested separately.

func TestIsSetUp_MissingConfig(t *testing.T) {
	dir := t.TempDir()
	if isSetUp(dir) {
		t.Errorf("isSetUp(empty dir) = true; want false")
	}
}

func TestIsSetUp_ConfigPresent_NoEnv(t *testing.T) {
	dir := t.TempDir()
	// The v2.1 case: wizard ran (config.json) but Telegram was skipped (no .env).
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if !isSetUp(dir) {
		t.Errorf("isSetUp(config.json, no .env) = false; want true — desktop-only is still set up")
	}
	if telegramEnabled(dir) {
		t.Errorf("telegramEnabled(no .env) = true; want false")
	}
}

func TestTelegramEnabled_MissingEnv(t *testing.T) {
	dir := t.TempDir()
	if telegramEnabled(dir) {
		t.Errorf("telegramEnabled(empty dir) = true; want false")
	}
}

func TestTelegramEnabled_TokenPresent_NoConfig(t *testing.T) {
	dir := t.TempDir()
	// Token present but no config.json — Telegram is "enabled" independently
	// of whether the wizard's other steps ran.
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=abc\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !telegramEnabled(dir) {
		t.Errorf("telegramEnabled(token present) = false; want true")
	}
	if isSetUp(dir) {
		t.Errorf("isSetUp(no config.json) = true; want false")
	}
}

func TestTelegramEnabled_EmptyToken(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if telegramEnabled(dir) {
		t.Errorf("telegramEnabled(empty token) = true; want false")
	}
}

func TestTelegramEnabled_WhitespaceToken(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=   \n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if telegramEnabled(dir) {
		t.Errorf("telegramEnabled(whitespace token) = true; want false")
	}
}

func TestTelegramEnabled_HappyPath(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=1234567890:abcdefghijklmnop\nTELEGRAM_CHAT_ID=123\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !telegramEnabled(dir) {
		t.Errorf("telegramEnabled(happy path) = false; want true")
	}
}

func TestTelegramEnabled_TokenWithComments(t *testing.T) {
	dir := t.TempDir()
	envContent := "# AMM environment\n# Generated by setup-wizard\nTELEGRAM_BOT_TOKEN=valid-token-here\nTELEGRAM_CHAT_ID=999\n"
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(envContent), 0o644); err != nil {
		t.Fatal(err)
	}
	if !telegramEnabled(dir) {
		t.Errorf("telegramEnabled(.env with comments) = false; want true")
	}
}
