package main

import (
	"os"
	"path/filepath"
	"testing"
)

// Tests for isConfigured — the v1.2.0 first-run gate.

func TestIsConfigured_MissingEverything(t *testing.T) {
	dir := t.TempDir()
	if isConfigured(dir) {
		t.Errorf("isConfigured(empty dir) = true; want false")
	}
}

func TestIsConfigured_MissingEnv(t *testing.T) {
	dir := t.TempDir()
	// config.json present but .env missing
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if isConfigured(dir) {
		t.Errorf("isConfigured(no .env) = true; want false")
	}
}

func TestIsConfigured_MissingConfig(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=abc\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if isConfigured(dir) {
		t.Errorf("isConfigured(no config.json) = true; want false")
	}
}

func TestIsConfigured_EmptyToken(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if isConfigured(dir) {
		t.Errorf("isConfigured(empty TELEGRAM_BOT_TOKEN) = true; want false")
	}
}

func TestIsConfigured_WhitespaceToken(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	// Only whitespace in the value — should be treated as empty
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=   \n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if isConfigured(dir) {
		t.Errorf("isConfigured(whitespace TELEGRAM_BOT_TOKEN) = true; want false")
	}
}

func TestIsConfigured_HappyPath(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{"active_profile":"default","profiles":{"default":{}}}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte("TELEGRAM_BOT_TOKEN=1234567890:abcdefghijklmnop\nTELEGRAM_CHAT_ID=123\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if !isConfigured(dir) {
		t.Errorf("isConfigured(happy path) = false; want true")
	}
}

func TestIsConfigured_TokenWithComments(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "config.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	// .env with comment lines + token — should still detect the token
	envContent := "# AMM environment\n# Generated by setup-wizard\nTELEGRAM_BOT_TOKEN=valid-token-here\nTELEGRAM_CHAT_ID=999\n"
	if err := os.WriteFile(filepath.Join(dir, ".env"), []byte(envContent), 0o644); err != nil {
		t.Fatal(err)
	}
	if !isConfigured(dir) {
		t.Errorf("isConfigured(.env with comments) = false; want true")
	}
}
