; Inno Setup script for Automatic Munyun Machine v1.2
; Build with: iscc installer\amm.iss
; Output: installer\dist\amm-setup-vX.Y.Z.exe
;
; v1.2: ships AMM.exe (Go tray wrapper) as the user-facing launcher.
; Start menu, desktop shortcut, and Add/Remove Programs all point at the
; wrapper instead of start-bot.cmd. Wrapper binary must be built BEFORE
; running iscc — see CI release.yml or `cd wrapper && make build`.
;
; Code signing: build the wrapper, sign it (scripts/build/sign-windows.ps1),
; THEN run iscc, THEN sign the resulting installer .exe. Both signatures
; are required for SmartScreen reputation.
;
; Requires Inno Setup 6.x — https://jrsoftware.org/isinfo.php

#define MyAppName "Automatic Munyun Machine"
#define MyAppShort "amm"
; MyAppVersion is normally injected by CI via `iscc /DMyAppVersion=X.Y.Z` so
; the installer filename always tracks package.json. The literal below is
; only a fallback for someone running `iscc` directly on a dev box — leave
; it pointing at the current release branch so local builds still produce
; a sensibly-named .exe.
#ifndef MyAppVersion
  #define MyAppVersion "7.9.0"
#endif
#define MyAppPublisher "Justin Williams"
#define MyAppURL "https://github.com/7ustoo/automatic-munyun-machine"
#define MyAppExeName "AMM.exe"
#define MyAppUserModelID "AutomaticMunyunMachine.Desktop"

; Preprocess-time check: the wrapper binary must exist before we package.
; This catches the most common build mistake (running `iscc` without first
; running `cd wrapper && make build`) at the right time — Inno Setup
; preprocess — instead of failing at the user's install time.
#if !FileExists(AddBackslash(SourcePath) + "..\wrapper\dist\AMM.exe")
  #error "wrapper\dist\AMM.exe not found. Build it first: cd wrapper && make build"
#endif

[Setup]
AppId={{E5E1A8C0-AMM1-4FA0-9C5E-AUTOMATICMUNYUN}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}/issues
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName={localappdata}\automatic-munyun-machine
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
OutputDir=dist
OutputBaseFilename=amm-setup-v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\wrapper\logo.ico
UninstallFilesDir={app}
; v2.0.1: brand the setup .exe itself (title-bar + Explorer icon).
; v2.0.2: full AMM logo (wrapper/logo.png; .ico generated by
; scripts/build/make-ico.mjs). Tray icons stay the color-coded
; icon-{green,yellow,red,gray}.ico set — those signal bot status.
SetupIconFile=..\wrapper\logo.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Ship the entire repo under {app}. Source path is one level up since the .iss
; lives in installer/.
;
; v2.0.1: node_modules is NO LONGER excluded — all runtime deps are pure JS
; (no native compilation), so CI's `npm ci` output ships inside the installer
; and the user never runs npm at install time. That kills the multi-minute
; silent "Installing dependencies" step that looked like a hang.
; v7.1: \config.json MUST stay excluded. CI's npm-test step creates a
; config.json in the checkout (config-rw copies the example on first read),
; and without this exclusion it shipped in the payload and — with
; ignoreversion — OVERWROTE the user's real config.json on every update:
; blocked companies, API key, schedule, email settings all reset. data\*
; and .env were always excluded, which is why profiles/resume survived
; while settings vanished. The leading backslash pins the pattern to the
; payload root so a dependency's own config.json (node_modules) still ships.
Source: "..\*"; DestDir: "{app}"; \
  Excludes: "\config.json,data\*,.env,.env.*,*.log,installer\dist\*,.git\*,.github\*,.claude\*,*.zip,*.tmp,node_modules\.cache\*"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; v1.2: Start menu + desktop shortcuts launch AMM.exe (the Go tray wrapper),
; which owns the system-tray icon and supervises the node bot.
; v2.0.1: shortcuts point at the branded .ico directly — AMM.exe itself only
; carries an embedded icon when built with the go-winres step (CI does this;
; see wrapper/Makefile build-win), so the .ico is the reliable source.
; v2.7: dropped the "Setup wizard" Start menu shortcut — first-run setup now
; lives in the dashboard, opened by AMM.exe itself. The terminal wizard
; (scripts/setup-wizard.mjs) survives as a dev escape hatch via `npm run setup`.
Name: "{group}\{#MyAppName}"; Filename: "{app}\wrapper\dist\AMM.exe"; IconFilename: "{app}\wrapper\logo.ico"; AppUserModelID: "{#MyAppUserModelID}"
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\wrapper\dist\AMM.exe"; IconFilename: "{app}\wrapper\logo.ico"; AppUserModelID: "{#MyAppUserModelID}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional tasks:"; Flags: unchecked

[Code]
// v2.0.1: AMM drives the user's installed Chrome/Edge via Playwright's
// `channel` option (see scripts/browser-launcher.mjs) — the 150 MB bundled
// Chromium download is only needed when NEITHER browser exists, which on
// Windows effectively never happens (Edge ships with the OS).
function SystemBrowserPresent(): Boolean;
begin
  Result :=
    FileExists(ExpandConstant('{commonpf64}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{commonpf32}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{localappdata}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{commonpf32}\Microsoft\Edge\Application\msedge.exe')) or
    FileExists(ExpandConstant('{commonpf64}\Microsoft\Edge\Application\msedge.exe'));
end;

function NeedsChromium(): Boolean;
begin
  Result := not SystemBrowserPresent();
end;

// v6.0: AMM's native Windows dashboard uses the Evergreen WebView2 Runtime.
// Microsoft documents these exact registry locations and product GUID for
// per-machine/per-user detection. A non-empty version other than 0.0.0.0
// means the shared runtime is available. If it is missing, the packaged
// Microsoft bootstrapper installs the architecture-appropriate runtime.
function WebView2VersionValid(Version: String): Boolean;
begin
  Result := (Version <> '') and (Version <> '0.0.0.0');
end;

function WebView2RuntimePresent(): Boolean;
var
  Version: String;
  ClientKey: String;
begin
  ClientKey := 'Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  Result :=
    (RegQueryStringValue(HKCU, ClientKey, 'pv', Version) and WebView2VersionValid(Version)) or
    (RegQueryStringValue(HKLM64, ClientKey, 'pv', Version) and WebView2VersionValid(Version)) or
    (RegQueryStringValue(HKLM32, ClientKey, 'pv', Version) and WebView2VersionValid(Version));
end;

function NeedsWebView2(): Boolean;
begin
  Result := (not WebView2RuntimePresent()) and
    FileExists(ExpandConstant('{app}\runtime\MicrosoftEdgeWebView2Setup.exe'));
end;

// v2.0.4: an install is "configured" when .env survives from a previous
// setup-wizard run. Gates the finish-page "Start AMM" checkbox: on upgrades
// the wizard is usually skipped, so without this the user ended the
// installer with nothing running and no hint that AMM must be started.
// Fresh installs don't need it — the wizard launches AMM at its last step.
function IsConfigured(): Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\.env'));
end;

// v2.4: stop a RUNNING AMM before copying files. Windows locks executables
// that are running, so upgrades over a live install silently failed to
// replace wrapper\dist\AMM.exe — the tray kept running the OLD binary until
// the next reboot, which made every "fixed in this release" look broken on
// upgraded machines. taskkill /T also takes down the supervised node bot
// child so nothing keeps polling with stale code either.
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode: Integer;
begin
  Exec(ExpandConstant('{sys}\taskkill.exe'), '/IM AMM.exe /T /F',
       '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  { taskkill exits non-zero when nothing matched — that's the normal
    fresh-install case, ignore it. Give the OS a beat to release file locks. }
  Sleep(800);
  Result := '';
end;

[Run]
; v6.0: provision Microsoft's shared Evergreen WebView2 Runtime only on the
; small set of Windows 10/11 machines where it is missing. The bootstrapper
; is Authenticode-verified in release.yml before being packaged. If runtime
; installation is blocked, AMM retains its Chrome/Edge app-mode fallback.
Filename: "{app}\runtime\MicrosoftEdgeWebView2Setup.exe"; \
  Parameters: "/silent /install"; \
  WorkingDir: "{app}"; \
  StatusMsg: "Installing the Microsoft WebView2 Runtime for AMM's native window…"; \
  Check: NeedsWebView2; \
  Flags: runhidden waituntilterminated

; Post-install. v2.0.1: npm install is GONE — node_modules ships inside the
; installer payload (see [Files]). Chromium download only runs when no
; system Chrome/Edge exists, and runs VISIBLE so its progress bar shows
; instead of a static "this may take a few minutes" message.
; v4.1.1: drive the BUNDLED node against the installed playwright-core CLI —
; a fresh machine has no system Node/npx, so the old `npx playwright …` line
; could not run (and only `playwright-core` ships in node_modules anyway).
Filename: "{app}\runtime\node.exe"; \
  Parameters: """{app}\node_modules\playwright-core\cli.js"" install chromium"; \
  WorkingDir: "{app}"; \
  StatusMsg: "No Chrome/Edge found — downloading Chromium (~150 MB)…"; \
  Check: NeedsChromium; \
  Flags: waituntilterminated

; v2.7: fresh installs and upgrades both launch AMM.exe — no terminal wizard.
; On fresh installs, the wrapper detects config.json is missing and its
; dashboard renders the first-run setup panel. On upgrades, the wrapper opens
; the normal dashboard. The wrapper's single-instance lock handles double-
; launches cleanly (the installer runs one, the user may launch from the
; desktop icon), and `skipifsilent` ensures silent installs don't pop windows.
Filename: "{app}\wrapper\dist\AMM.exe"; \
  WorkingDir: "{app}"; \
  Description: "Start {#MyAppName} (opens the setup dashboard on first launch)"; \
  Flags: postinstall nowait skipifsilent

[UninstallRun]
; v1.0 E6 — call uninstall.mjs in wipe mode so Add/Remove Programs gives
; the user a real cleanup, not just an "uninstall" that leaves the bot
; running and the secrets on disk.
; v4.1.1: use the bundled runtime (still present — [UninstallDelete] runs
; after this) instead of a bare "node.exe" off PATH, which is absent on
; machines that never had system Node.
Filename: "{app}\runtime\node.exe"; \
  Parameters: """{app}\scripts\uninstall.mjs"" --mode=wipe"; \
  WorkingDir: "{app}"; \
  Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}\node_modules"
Type: filesandordirs; Name: "{app}\runtime"
Type: filesandordirs; Name: "{app}\data"
Type: filesandordirs; Name: "{app}"
