; Inno Setup script for Automatic Munyun Machine v1.2
; Build with: iscc installer\amm.iss
; Output: installer\dist\amm-setup-vX.Y.Z.exe
;
; v1.2: ships AMM.exe (Go tray wrapper) as the user-facing launcher.
; Start menu, desktop shortcut, and Add/Remove Programs all point at the
; wrapper instead of start-bot.cmd. Wrapper binary must be built BEFORE
; running iscc — see CI release.yml or `cd wrapper && make build`.
;
; Code signing: build the wrapper, sign it (scripts/build/sign-windows.ps1),
; THEN run iscc, THEN sign the resulting installer .exe. Both signatures
; are required for SmartScreen reputation.
;
; Requires Inno Setup 6.x — https://jrsoftware.org/isinfo.php

#define MyAppName "Automatic Munyun Machine"
#define MyAppShort "amm"
; MyAppVersion is normally injected by CI via `iscc /DMyAppVersion=X.Y.Z` so
; the installer filename always tracks package.json. The literal below is
; only a fallback for someone running `iscc` directly on a dev box — leave
; it pointing at the current release branch so local builds still produce
; a sensibly-named .exe.
#ifndef MyAppVersion
  #define MyAppVersion "1.3.0"
#endif
#define MyAppPublisher "Justin Williams"
#define MyAppURL "https://github.com/7ustoo/automatic-munyun-machine"
#define MyAppExeName "AMM.exe"

; Preprocess-time check: the wrapper binary must exist before we package.
; This catches the most common build mistake (running `iscc` without first
; running `cd wrapper && make build`) at the right time — Inno Setup
; preprocess — instead of failing at the user's install time.
#if !FileExists(AddBackslash(SourcePath) + "..\wrapper\dist\AMM.exe")
  #error "wrapper\dist\AMM.exe not found. Build it first: cd wrapper && make build"
#endif

[Setup]
AppId={{E5E1A8C0-AMM1-4FA0-9C5E-AUTOMATICMUNYUN}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}/issues
AppUpdatesURL={#MyAppURL}/releases
DefaultDirName={localappdata}\automatic-munyun-machine
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
OutputDir=dist
OutputBaseFilename=amm-setup-v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\wrapper\logo.ico
UninstallFilesDir={app}
; v2.0.1: brand the setup .exe itself (title-bar + Explorer icon).
; v2.0.2: full AMM logo (wrapper/logo.png; .ico generated by
; scripts/build/make-ico.mjs). Tray icons stay the color-coded
; icon-{green,yellow,red,gray}.ico set — those signal bot status.
SetupIconFile=..\wrapper\logo.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Ship the entire repo under {app}. Source path is one level up since the .iss
; lives in installer/.
;
; v2.0.1: node_modules is NO LONGER excluded — all runtime deps are pure JS
; (no native compilation), so CI's `npm ci` output ships inside the installer
; and the user never runs npm at install time. That kills the multi-minute
; silent "Installing dependencies" step that looked like a hang.
Source: "..\*"; DestDir: "{app}"; \
  Excludes: "data\*,.env,.env.*,*.log,installer\dist\*,.git\*,.github\*,.claude\*,*.zip,*.tmp,node_modules\.cache\*"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
; v1.2: Start menu + desktop shortcuts launch AMM.exe (the Go tray wrapper),
; which owns the system-tray icon and supervises the node bot.
; v2.0.1: shortcuts point at the branded .ico directly — AMM.exe itself only
; carries an embedded icon when built with the go-winres step (CI does this;
; see wrapper/Makefile build-win), so the .ico is the reliable source.
Name: "{group}\{#MyAppName}"; Filename: "{app}\wrapper\dist\AMM.exe"; IconFilename: "{app}\wrapper\logo.ico"
Name: "{group}\Setup wizard"; Filename: "{app}\scripts\setup-wizard.mjs"
Name: "{group}\Uninstall"; Filename: "{uninstallexe}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\wrapper\dist\AMM.exe"; IconFilename: "{app}\wrapper\logo.ico"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "Create a desktop shortcut"; GroupDescription: "Additional tasks:"; Flags: unchecked

[Code]
// v2.0.1: AMM drives the user's installed Chrome/Edge via Playwright's
// `channel` option (see scripts/browser-launcher.mjs) — the 150 MB bundled
// Chromium download is only needed when NEITHER browser exists, which on
// Windows effectively never happens (Edge ships with the OS).
function SystemBrowserPresent(): Boolean;
begin
  Result :=
    FileExists(ExpandConstant('{commonpf64}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{commonpf32}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{localappdata}\Google\Chrome\Application\chrome.exe')) or
    FileExists(ExpandConstant('{commonpf32}\Microsoft\Edge\Application\msedge.exe')) or
    FileExists(ExpandConstant('{commonpf64}\Microsoft\Edge\Application\msedge.exe'));
end;

function NeedsChromium(): Boolean;
begin
  Result := not SystemBrowserPresent();
end;

// v2.0.4: an install is "configured" when .env survives from a previous
// setup-wizard run. Gates the finish-page "Start AMM" checkbox: on upgrades
// the wizard is usually skipped, so without this the user ended the
// installer with nothing running and no hint that AMM must be started.
// Fresh installs don't need it — the wizard launches AMM at its last step.
function IsConfigured(): Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\.env'));
end;

[Run]
; Post-install. v2.0.1: npm install is GONE — node_modules ships inside the
; installer payload (see [Files]). Chromium download only runs when no
; system Chrome/Edge exists, and runs VISIBLE so its progress bar shows
; instead of a static "this may take a few minutes" message.
Filename: "cmd.exe"; \
  Parameters: "/C ""npx playwright install chromium"""; \
  WorkingDir: "{app}"; \
  StatusMsg: "No Chrome/Edge found — downloading Chromium (~150 MB)…"; \
  Check: NeedsChromium; \
  Flags: waituntilterminated

Filename: "node.exe"; \
  Parameters: """{app}\scripts\setup-wizard.mjs"""; \
  WorkingDir: "{app}"; \
  Description: "Run the {#MyAppName} setup wizard"; \
  Flags: postinstall nowait

; v2.0.4: upgrades over a configured install (.env exists) usually skip the
; wizard — start the tray app straight from the finish page instead. The
; wrapper's single-instance lock makes an accidental double-launch (wizard
; checked too) exit cleanly. Fresh installs never see this entry; the
; wizard's last step launches AMM and explains the tray icon.
Filename: "{app}\wrapper\dist\AMM.exe"; \
  WorkingDir: "{app}"; \
  Description: "Start {#MyAppName} in the system tray (required for the bot to work)"; \
  Check: IsConfigured; \
  Flags: postinstall nowait skipifsilent

[UninstallRun]
; v1.0 E6 — call uninstall.mjs in wipe mode so Add/Remove Programs gives
; the user a real cleanup, not just an "uninstall" that leaves the bot
; running and the secrets on disk.
Filename: "node.exe"; \
  Parameters: """{app}\scripts\uninstall.mjs"" --mode=wipe"; \
  WorkingDir: "{app}"; \
  Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}\node_modules"
Type: filesandordirs; Name: "{app}\data"
Type: filesandordirs; Name: "{app}"
